In [1]:
import tensorflow as tf

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# why divide by 255?

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.3050685 , -0.00898894, -0.30652612, -0.45320386,  0.05093848,
        -0.62992   ,  0.17331779, -0.3132609 , -0.00213473,  0.2519874 ]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.14267725, 0.10422246, 0.07740028, 0.06684074, 0.11065918,
        0.05601371, 0.1250651 , 0.07688076, 0.10493927, 0.13530128]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.8821588

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2931 - accuracy: 0.9153
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1423 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1068 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0879 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0739 - accuracy: 0.9769


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0760 - accuracy: 0.9764


[0.07603820413351059, 0.9764000177383423]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.06669852e-07, 8.45393444e-09, 1.25409133e-06, 1.02698956e-04,
        4.50876225e-10, 4.81892869e-07, 5.54655944e-14, 9.99878526e-01,
        1.35749360e-07, 1.67387207e-05],
       [5.70205088e-07, 2.57966458e-04, 9.99450862e-01, 2.04660173e-04,
        1.84661612e-13, 7.50127583e-05, 4.86750878e-06, 2.20680973e-11,
        5.97616827e-06, 1.27218887e-13],
       [6.34109142e-07, 9.91433740e-01, 8.21208523e-04, 3.13669807e-05,
        3.32963282e-05, 2.92775567e-05, 3.26095149e-04, 6.80949306e-03,
        5.14344836e-04, 4.28225349e-07],
       [9.99808371e-01, 5.00899278e-09, 1.38367002e-04, 2.56121325e-06,
        2.72985221e-06, 1.32873929e-05, 9.89795080e-06, 1.46958291e-05,
        4.60056491e-08, 1.00386824e-05],
       [8.65489369e-07, 4.13820367e-10, 1.09038126e-06, 6.97548117e-08,
        9.93698716e-01, 1.36262042e-06, 5.40064411e-06, 1.03277664e-04,
        1.23206146e-05, 6.17691549e-03]], dtype=float32)>